[INPUTDATA]
Number of training data						= 60000
Number of input units						= 784
Number of output units 						= 10
Number of hidden layers						= 2
Number of units in layer 0					= 56
Number of units in layer 1					= 28
Max number of epochs						= 3
Number of threads                           = 4
Learning rate 							= 0.0002
Momentum							= 0.002
Initialization scale						= 0.2
Error threshold							= 10.
Input file name							= "train-input"
Target file name						= "train-output"
Results file name						= "train-results"
Result delta file name						= "delta-results"
Restart file name						= "train-restart"
Restart delta file name						= "delta-restart"
Log file name							= "NNML.log"
